name: Build Raspberry Pi Image

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Enable binfmt_misc
      run: |
        sudo modprobe binfmt_misc || echo "binfmt_misc already loaded"
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build Raspberry Pi Image
      run: |
        chmod +x build.sh
        ./build.sh

    - name: List generated files
      run: |
        find . -name "*.img" -type f -exec ls -lh {} \;

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: raspberry-pi-image
        path: "*/deploy/*.img"
        retention-days: 30

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: "*/deploy/*.img"
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}